In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import glob as gb

In [3]:
pwd

'C:\\Users\\choir\\Documents\\GitHub\\TDSN_SOBI\\Code'

In [4]:
data1 = pd.read_csv("C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Transportasi/agustus-2019-data-kecepatan-rata-rata-di-41-koridor-jalan-utama-pada-jam-sibuk.csv")

In [5]:
data1.describe()

,target_kecepatan,jarak,target_waktu_tempuh,pencapaian_kecepatan_per_koridor,pencapaian_kecepatan,pencapaian_waktu_tempuh
count,82.0,82.000000,82.000000,82.000000,82.000000,82.000000
mean,21.0,15.028780,42.939268,25.857195,25.858902,40.727073
std,0.0,3.056263,8.732337,5.091508,3.822739,12.144601
min,21.0,8.450000,24.140000,15.520000,20.220000,14.210000
25%,21.0,13.130000,37.510000,22.432500,23.240000,30.987500
50%,21.0,14.670000,41.910000,25.385000,24.360000,39.840000
75%,21.0,17.050000,48.710000,28.680000,28.810000,50.675000
max,21.0,21.210000,60.600000,39.680000,33.800000,70.030000

In [7]:
data1.head(3)

,waktu,arah,koridor,target_kecepatan,jarak,target_waktu_tempuh,pencapaian_kecepatan_per_koridor,pencapaian_kecepatan,pencapaian_waktu_tempuh
0,pagi,Selatan - Pusat,Lenteng Agung - Ps. Minggu - Supomo - dr. Saha...,21,19.62,56.06,22.77,24.36,58.82
1,pagi,Selatan - Pusat,Cilandak KKO - Warung Buncit - Mampang Prapata...,21,13.36,38.17,24.14,24.36,36.88
2,pagi,Selatan - Pusat,Pangeran Antasari - Prapanca - Iskandarsyah - ...,21,11.13,31.80,29.64,24.36,25.99

In [9]:
print(data1['waktu'].unique())
print(data1['arah'].unique())

['pagi' 'sore']
['Selatan - Pusat' 'Timur - Pusat' 'Utara - Pusat' 'Barat - Pusat'
 'Pusat - Selatan' 'Pusat - Timur' 'Pusat - Utara' 'Pusat - Barat']

In [11]:
data_2 = pd.read_csv('C:/Users/Choir/Documents/GitHub/TDSN_SOBI/Datasource/Public Service/DKI Jakarta/Transportasi/\
data-armada-angkutan-umum-2017.csv')

In [12]:
data_2.head(5)

  jenis_kendaraan                nama_perusahaan  jumlah_unit
0       Bus Besar       PT. Transportasi Jakarta          1666
1       Bus Besar             PT. Mayasari Bakti           881
2       Bus Besar      PT. Koda Jaya / AJA Putra            12
3       Bus Besar  PT. Sinar Jaya Megah Langgeng            18
4       Bus Besar     PT. Bianglala Metropolitan            45